import type { Metadata } from "next";
import { Inria_Serif } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inriaSerif = Inria_Serif({
  weight: ['400', '700'], // Specify the weights you need
  subsets: ['latin'], // Specify the subsets
  display: 'swap', // Use 'swap' to avoid invisible text during loading
  variable: '--font-inria-serif', // Optional: for using with CSS variables or Tailwind
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inriaSerif.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
